enum KubeResources {
    apiservices
    authcodes
    authrequests
    backups
    backupstoragelocations
    bindings
    bsl
    certificatesigningrequests
    cj
    clusterrolebindings
    clusterroles
    cm
    componentstatuses
    configmaps
    connectors
    controllerrevisions
    crd
    crds
    cronjobs
    cs
    csidrivers
    csinodes
    csistoragecapacities
    csr
    customresourcedefinitions
    daemonsets
    deletebackuprequests
    deploy
    deployments
    devicerequests
    devicetokens
    downloadrequests
    ds
    endpoints
    endpointslices
    ep
    ev
    events
    flowschemas
    horizontalpodautoscalers
    hpa
    ing
    ingressclasses
    ingresses
    jobs
    khs
    khstates
    leases
    limitranges
    limits
    localsubjectaccessreviews
    mutatingwebhookconfigurations
    namespaces
    netpol
    networkpolicies
    no
    nodes
    ns
    oauth2clients
    offlinesessionses
    passwords
    pc
    pdb
    persistentvolumeclaims
    persistentvolumes
    po
    poddisruptionbudgets
    pods
    podtemplates
    podvolumebackups
    podvolumerestores
    priorityclasses
    prioritylevelconfigurations
    pv
    pvc
    quota
    rc
    refreshtokens
    replicasets
    replicationcontrollers
    resourcequotas
    resticrepositories
    restores
    rolebindings
    roles
    rs
    runtimeclasses
    sa
    sc
    schedules
    secrets
    selfsubjectaccessreviews
    selfsubjectreviews
    selfsubjectrulesreviews
    serverstatusrequests
    serviceaccounts
    services
    signingkeies
    ssr
    statefulsets
    storageclasses
    sts
    subjectaccessreviews
    svc
    tokenreviews
    validatingwebhookconfigurations
    volumeattachments
    volumesnapshotlocations
}
